name: Deploy to WordPress.org Repository
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (e.g. 0.21.2)'
        required: true

permissions:
  contents: read
  id-token: write
  actions: read
  deployments: write
  packages: read

jobs:
  deploy_to_wp_repository:
    name: Deploy to WP.org
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        ref: ${{ inputs.tag || github.ref }}
    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@2.3.0
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: smart-tags-optimizer
        VERSION: ${{ inputs.tag }}
